services:
  - type: web
    name: myportifolio
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://myportifolio-1-xdlo.onrender.com,https://my-portifolio-dnzecgwui-mohameds-projects-f8a525fa.vercel.app,http://localhost:5173
